name: Backup
on:
  schedule:
    - cron: 0 8,20 * * *
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install lftp touch -y
          mkdir ${{ secrets.FTP_LOCAL }}
          touch ~/.ssh/config
          echo StrictHostKeyChecking accept-new > ~/.ssh/config

      - name: Get backups from Minecraft server
        run: |
          lftp ${{ secrets.FTP_HOST }} -p ${{ secrets.FTP_PORT }} -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} -e "mirror --only-newer --ignore-time --continue --delete ${{ secrets.FTP_REMOTE }} ${{ secrets.FTP_LOCAL }}; quit;"

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          filename: "${{ secrets.FTP_LOCAL }}/*"
          folderId: ${{ secrets.GCP_FOLDER_ID }}
          overwrite: true
