name: Backup
on:
  schedule:
    #- cron: 0 8,20 * * *
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Make backup temp folder
        run: |
          mkdir ${{ secrets.FTP_LOCAL }}
      
      - name: Get backups from Minecraft server
        run: |
          lftp ${{ secrets.FTP_HOST }} -p ${{ secrets.FTP_PORT }} -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} -e "set ftp:ssl-force false; set ssl:verify-certificate false; mirror --only-newer --ignore-time --continue --delete ${{ secrets.FTP_REMOTE }} ${{ secrets.FTP_LOCAL }}; quit;"

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          filename: "${{ secrets.FTP_LOCAL }}/*"
          folderId: ${{ secrets.GCP_FOLDER_ID }}
