name: Backup
on:
  schedule:
    #- cron: 0 0,4,8,12,16,20 * * *
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up environment
        run: |
          cd backup
          pip install --upgrade py-dactyl google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Backing up files
        run: |
          cd backup
          python backup.py
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GCP_FOLDER_ID: ${{ secrets.GCP_FOLDER_ID }}
          SERVER_BACKUP_FOLDER: backup
          PENTADACTYL_HOST: ${{ secrets.PENTADACTYL_HOST }}
          PENTADACTYL_KEY: ${{ secrets.PENTADACTYL_KEY }}
          PENTADACTYL_SERVER: ${{ secrets.PENTADACTYL_SERVER }}